- name: Install Jenkins Master
  hosts: master
  gather_facts: true
  roles:
    - role: jenkins
      tags: jenkins-master

- name: Install Docker and Jenkins Slave
  hosts: slave
  gather_facts: true
  roles:
    - role: docker
      tags: docker
    - role: jenkins-slave
      tags: jenkins-slave 