---
# handlers for jenkins role

- name: start and enable jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes

- name: restart jenkins
  ansible.builtin.service:
    name: jenkins
    state: restarted

- name: restart squid
  ansible.builtin.service:
    name: squid
    state: restarted
