---
# tasks file for jenkins

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Java and required packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - fontconfig
    - openjdk-21-jre
    - wget
    - gnupg
    - squid

- name: Configure Squid proxy
  ansible.builtin.template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart squid

- name: Start and enable Squid service
  ansible.builtin.service:
    name: squid
    state: started
    enabled: yes

- name: Create Jenkins key directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins GPG key
  ansible.builtin.get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
  notify: start and enable jenkins